apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: object-detection-rest
    app.kubernetes.io/component: object-detection-rest
    app.kubernetes.io/instance: object-detection-rest
  name: object-detection-rest
  namespace: "retail-prod-rhods-project"
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: object-detection-rest:latest
  runPolicy: Serial
  source:
    git:
      uri: uri: https://gitea.apps.cluster-guid.ocp4_base_domain/lab-user/arc-model.git
      ref: main
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python:3.9-ubi8
        namespace: openshift
    type: Source
  triggers:
    - type: ConfigChange
  successfulBuildsHistoryLimit: 5
      uri: https://gitea.apps.cluster-45mw6.sandbox1558.opentlc.com/lab-user/arc-model.git
