---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: "rhods-object-detect-rest-template"
  namespace: "retail-prod-rhods-project"
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
      labels:
        app.kubernetes.io/instance: object-detection-rest
        app.kubernetes.io/name: object-detection-rest
        pipeline.openshift.io/runtime: python
        pipeline.openshift.io/runtime-version: 3.9-ubi8
        pipeline.openshift.io/type: kubernetes
        tekton.dev/pipeline: object-detection-rest
      generateName: object-detection-rest-
      namespace: "retail-prod-rhods-project"
    spec:
      params:
      - name: APP_NAME
        value: "object-detection-rest"
      - name: GIT_REPO
        value: "https://gitea.apps.cluster-45mw6.sandbox1558.opentlc.com/lab-user/arc-model.git"
      - name: GIT_REVISION
        value: ""
      - name: IMAGE_NAME
        value: "image-registry.openshift-image-registry.svc:5000/retail-prod-rhods-project/object-detection-rest"
      - name: PATH_CONTEXT
        value: .
      - name: VERSION
        value: 3.9-ubi8
      pipelineRef:
        name: object-detection-rest
      serviceAccountName: pipeline
      timeout: 1h0m0s
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: workspace-pvc
